version: '3'

services:
    web-prod:
        build:
            context: ./services/web
            dockerfile: Dockerfile-PROD
            args:
                - http_proxy
                - https_proxy
        networks:
            - prod
        restart: on-failure
        links:
            - db-prod:db
        env_file:
            - ./services/web/docker-PROD.env
        depends_on:
            - db-prod

    db-prod:
        build:
            context: ./services/db
            dockerfile: Dockerfile-PROD
            args:
                - http_proxy
                - https_proxy
        networks:
            - prod
        restart: on-failure
        ports:
            - 3306:3306
        volumes:
            - mysql-prod:/var/lib/mysql
        env_file:
            - ./services/db/docker-PROD.env
        command: --explicit_defaults_for_timestamp

    nginx-prod:
        build:
            context: ./services/nginx
            dockerfile: Dockerfile-PROD
            args:
                - http_proxy
                - https_proxy
        networks:
            - prod
        restart: on-failure
        ports:
            - 80:80
            - 443:443
        links:
            - web-prod:web
        depends_on:
            - web-prod

networks:
    prod:
        driver: bridge

volumes:
    mysql-prod:
        driver: local
