version: '3'

services:
    web:
        build:
            context: ./services/web
            dockerfile: Dockerfile
        restart: on-failure
        volumes:
            - './services/web/migrations:/usr/src/app/migrations'
        expose:
            - 5000
        links:
            - db:db
        env_file:
            - ./services/web/docker.env
        depends_on:
            - db

    db:
        build:
            context: ./services/db
            dockerfile: Dockerfile
        restart: on-failure
        ports:
            - 3306:3306
        volumes:
            - mysql:/var/lib/mysql
        env_file:
            - ./services/db/docker.env
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --explicit_defaults_for_timestamp

    nginx:
        build:
            context: ./services/nginx
            dockerfile: Dockerfile
        restart: on-failure
        ports:
            - 80:80
            - 443:443
        links:
            - web:web
        depends_on:
            - web

volumes:
    mysql:
        driver: local
