version: '3'

services:
    web:
        build:
            context: ./services/web
            dockerfile: Dockerfile
        restart: on-failure
        volumes:
            - './services/web:/usr/src/app'
        expose:
            - 5000
        links:
            - db:db
        env_file:
            - ./services/web/docker.env
        depends_on:
            - db

    db:
        build:
            context: ./services/web/project/db
            dockerfile: Dockerfile
        restart: on-failure
        ports:
            - 5435:5432
        volumes:
            - postgres:/var/lib/postgresql/data
        env_file:
            - ./services/web/project/db/docker.env

    nginx:
        build:
            context: ./services/nginx
            dockerfile: Dockerfile
        restart: on-failure
        ports:
            - 80:80
            - 443:443
        links:
            - web:web
        depends_on:
            - web

volumes:
    postgres:
        driver: local
