"""empty message

Revision ID: b7a8e0f623c8
Revises: 
Create Date: 2019-01-15 22:36:11.713969

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b7a8e0f623c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('modified_time', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('event_attack_vector',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_table('event_disposition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_table('event_prevention_tool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_table('event_remediation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_table('event_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_table('event_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_table('indicator_confidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_table('indicator_impact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_table('indicator_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_table('indicator_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_table('intel_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_table('malware',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('malware_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('apikey', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('apikey'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('campaign_alias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.Column('_campaign_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['_campaign_id'], ['campaign.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('_campaign_id', sa.Integer(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('_disposition_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('_status_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['_campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['_disposition_id'], ['event_disposition.id'], ),
    sa.ForeignKeyConstraint(['_status_id'], ['event_status.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('indicator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_sensitive', sa.Boolean(), nullable=False),
    sa.Column('_confidence_id', sa.Integer(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('_impact_id', sa.Integer(), nullable=False),
    sa.Column('modified_time', sa.DateTime(), nullable=True),
    sa.Column('_status_id', sa.Integer(), nullable=False),
    sa.Column('substring', sa.Boolean(), nullable=False),
    sa.Column('_type_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['_confidence_id'], ['indicator_confidence.id'], ),
    sa.ForeignKeyConstraint(['_impact_id'], ['indicator_impact.id'], ),
    sa.ForeignKeyConstraint(['_status_id'], ['indicator_status.id'], ),
    sa.ForeignKeyConstraint(['_type_id'], ['indicator_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('_type_id', 'value')
    )
    op.create_table('intel_reference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('_user_id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=512), nullable=False),
    sa.Column('_intel_source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['_intel_source_id'], ['intel_source.id'], ),
    sa.ForeignKeyConstraint(['_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('_intel_source_id', 'reference')
    )
    op.create_index(op.f('ix_intel_reference_reference'), 'intel_reference', ['reference'], unique=False)
    op.create_table('malware_type_mapping',
    sa.Column('malware_id', sa.Integer(), nullable=True),
    sa.Column('malware_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['malware_id'], ['malware.id'], ),
    sa.ForeignKeyConstraint(['malware_type_id'], ['malware_type.id'], )
    )
    op.create_table('role_user_mapping',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('event_attack_vector_mapping',
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('event_attack_vector_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_attack_vector_id'], ['event_attack_vector.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], )
    )
    op.create_table('event_malware_mapping',
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('malware_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['malware_id'], ['malware.id'], )
    )
    op.create_table('event_prevention_tool_mapping',
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('event_prevention_tool_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['event_prevention_tool_id'], ['event_prevention_tool.id'], )
    )
    op.create_table('event_reference_mapping',
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('intel_reference_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['intel_reference_id'], ['intel_reference.id'], )
    )
    op.create_table('event_remediation_mapping',
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('event_remediation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['event_remediation_id'], ['event_remediation.id'], )
    )
    op.create_table('event_tag_mapping',
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    op.create_table('event_type_mapping',
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('event_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['event_type_id'], ['event_type.id'], )
    )
    op.create_table('indicator_campaign_mapping',
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('indicator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicator.id'], )
    )
    op.create_table('indicator_equal_mapping',
    sa.Column('left_id', sa.Integer(), nullable=False),
    sa.Column('right_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['left_id'], ['indicator.id'], ),
    sa.ForeignKeyConstraint(['right_id'], ['indicator.id'], ),
    sa.PrimaryKeyConstraint('left_id', 'right_id')
    )
    op.create_table('indicator_reference_mapping',
    sa.Column('indicator_id', sa.Integer(), nullable=True),
    sa.Column('intel_reference_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicator.id'], ),
    sa.ForeignKeyConstraint(['intel_reference_id'], ['intel_reference.id'], )
    )
    op.create_table('indicator_relationship_mapping',
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['indicator.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['indicator.id'], ),
    sa.PrimaryKeyConstraint('parent_id', 'child_id')
    )
    op.create_table('indicator_tag_mapping',
    sa.Column('indicator_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicator.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('indicator_tag_mapping')
    op.drop_table('indicator_relationship_mapping')
    op.drop_table('indicator_reference_mapping')
    op.drop_table('indicator_equal_mapping')
    op.drop_table('indicator_campaign_mapping')
    op.drop_table('event_type_mapping')
    op.drop_table('event_tag_mapping')
    op.drop_table('event_remediation_mapping')
    op.drop_table('event_reference_mapping')
    op.drop_table('event_prevention_tool_mapping')
    op.drop_table('event_malware_mapping')
    op.drop_table('event_attack_vector_mapping')
    op.drop_table('role_user_mapping')
    op.drop_table('malware_type_mapping')
    op.drop_index(op.f('ix_intel_reference_reference'), table_name='intel_reference')
    op.drop_table('intel_reference')
    op.drop_table('indicator')
    op.drop_table('event')
    op.drop_table('campaign_alias')
    op.drop_table('user')
    op.drop_table('tag')
    op.drop_table('role')
    op.drop_table('malware_type')
    op.drop_table('malware')
    op.drop_table('intel_source')
    op.drop_table('indicator_type')
    op.drop_table('indicator_status')
    op.drop_table('indicator_impact')
    op.drop_table('indicator_confidence')
    op.drop_table('event_type')
    op.drop_table('event_status')
    op.drop_table('event_remediation')
    op.drop_table('event_prevention_tool')
    op.drop_table('event_disposition')
    op.drop_table('event_attack_vector')
    op.drop_table('campaign')
    # ### end Alembic commands ###
