"""empty message

Revision ID: f8bf8a5c24c9
Revises: 
Create Date: 2019-01-19 06:19:46.850173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8bf8a5c24c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('_user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'event', 'user', ['_user_id'], ['id'])
    op.add_column('indicator', sa.Column('_user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'indicator', 'user', ['_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'indicator', type_='foreignkey')
    op.drop_column('indicator', '_user_id')
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.drop_column('event', '_user_id')
    # ### end Alembic commands ###
