"""empty message

Revision ID: fc9854dd0bc0
Revises: 
Create Date: 2019-03-11 16:37:10.472196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc9854dd0bc0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('modified_time', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('indicator_confidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_table('indicator_impact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_table('indicator_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_table('indicator_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_table('intel_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('apikey', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=130), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_user_apikey'), 'user', ['apikey'], unique=True)
    op.create_table('campaign_alias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias')
    )
    op.create_table('indicator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_sensitive', sa.Boolean(), nullable=False),
    sa.Column('confidence_id', sa.Integer(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('impact_id', sa.Integer(), nullable=False),
    sa.Column('modified_time', sa.DateTime(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('substring', sa.Boolean(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.UnicodeText(), nullable=False),
    sa.ForeignKeyConstraint(['confidence_id'], ['indicator_confidence.id'], ),
    sa.ForeignKeyConstraint(['impact_id'], ['indicator_impact.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['indicator_status.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['indicator_type.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intel_reference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=512), nullable=False),
    sa.Column('intel_source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['intel_source_id'], ['intel_source.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('intel_source_id', 'reference')
    )
    op.create_index(op.f('ix_intel_reference_reference'), 'intel_reference', ['reference'], unique=False)
    op.create_table('role_user_mapping',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('indicator_campaign_mapping',
    sa.Column('indicator_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicator.id'], )
    )
    op.create_table('indicator_equal_mapping',
    sa.Column('left_id', sa.Integer(), nullable=False),
    sa.Column('right_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['left_id'], ['indicator.id'], ),
    sa.ForeignKeyConstraint(['right_id'], ['indicator.id'], ),
    sa.PrimaryKeyConstraint('left_id', 'right_id')
    )
    op.create_table('indicator_reference_mapping',
    sa.Column('indicator_id', sa.Integer(), nullable=True),
    sa.Column('intel_reference_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicator.id'], ),
    sa.ForeignKeyConstraint(['intel_reference_id'], ['intel_reference.id'], )
    )
    op.create_table('indicator_relationship_mapping',
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['indicator.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['indicator.id'], ),
    sa.PrimaryKeyConstraint('parent_id', 'child_id')
    )
    op.create_table('indicator_tag_mapping',
    sa.Column('indicator_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicator.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('indicator_tag_mapping')
    op.drop_table('indicator_relationship_mapping')
    op.drop_table('indicator_reference_mapping')
    op.drop_table('indicator_equal_mapping')
    op.drop_table('indicator_campaign_mapping')
    op.drop_table('role_user_mapping')
    op.drop_index(op.f('ix_intel_reference_reference'), table_name='intel_reference')
    op.drop_table('intel_reference')
    op.drop_table('indicator')
    op.drop_table('campaign_alias')
    op.drop_index(op.f('ix_user_apikey'), table_name='user')
    op.drop_table('user')
    op.drop_table('tag')
    op.drop_table('role')
    op.drop_table('intel_source')
    op.drop_table('indicator_type')
    op.drop_table('indicator_status')
    op.drop_table('indicator_impact')
    op.drop_table('indicator_confidence')
    op.drop_table('campaign')
    # ### end Alembic commands ###
