FROM python:3.7

ARG http_proxy
ARG https_proxy

RUN apt-get update && apt-get install -y mariadb-client python3-dev default-libmysqlclient-dev

WORKDIR /usr/src/app

COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt

COPY ./entrypoint-DEV.sh /usr/src/app/entrypoint-DEV.sh
COPY . /usr/src/app

CMD ["/usr/src/app/entrypoint-DEV.sh"]
