FROM pypy:3

ARG http_proxy
ARG https_proxy

RUN apt-get update && apt-get install -y mysql-client

WORKDIR /usr/src/app

COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt

COPY ./entrypoint-TEST.sh /usr/src/app/entrypoint-TEST.sh
COPY . /usr/src/app

CMD ["/usr/src/app/entrypoint-TEST.sh"]
